### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by de2apandi** [raqtor1/spankbang-scraper#1]
hello thanks for great project

i got error or something when i use google colab i got error like this
```
Traceback (most recent call last):
  File "/content/spankbang-scraper/scraper.py", line 17, in <module>
    full_video = item.find("a", class_='thumb')['href']
TypeError: 'NoneType' object is not subscriptable
```

but when use powershell on windows it works , but just single link output, before i set number or search 8 or 20
not work

please help thanks

**Comment by raqtor1** [comment]
Hello.

Can I get what you haves searched for and the number of videos you chose to output so I can reproduce this issue?

**Comment by raqtor1** [comment]
Ok, I have updated the code now. Make sure to clone the latest one. Feel free to open another issue if you find any other errors. Thank you.
